### PR TITLE
Create service_container.yml

### LINKED ISSUE #2: Using this as a GitHub service container?
The current `apt-get install inn2` approach used to run pynntp pytests is unreliable and fails to install unpredictably.

The approach in this repo seems reliable but has two problems:
1. #1
2. We need to access this container within a GitHub Action.
    * https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #2
* #2 

To use this in a GitHub Action please add:
```yaml
    services:
      inn-service:
        image: greenbender/inn
        ports:
          - 119:119
          - 563:563
```

### CODE REVIEW

**Comment by greenbender** [comment]
Doesn't this belong in `pynntp`? Are you just testing it here?

**Comment by cclauss** [comment]
Yes.  Once it works we can copy to pynntp but I am confused about the syntax.

**Comment by greenbender** [comment]
I would be tempted to not run the test inside the conatiner?

Just expose port 119 on the gh runner host like this example.
https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers#example-mapping-redis-ports

~~I assume all you need to do then is add `needs` to the test `job` so that things run in order~~

**Comment by cclauss** [comment]
Given #5, should we
* [ ] Remove the line `- 563:563`
* [ ] `# - 563:563`
* [ ] `# - 563:563  # See: greenbender/inn-docker#5`
* [ ] `# - 563:563  # See: https://github.com/greenbender/inn-docker/issues/5`

**Review by greenbender — APPROVED** [review]

**Pull request merged**
